from __future__ import annotations

from research_lab.strategies import (
    bollinger_mean_reversion_simple,
    bollinger_mean_reversion_adx_low,
    donchian_breakout_regime,
    ema_trend_pullback,
    keltner_volatility_expansion_simple,
    keltner_squeeze_breakout,
    supertrend_ema_filter,
    strategy_smr,
    strategy_ls_sr,
    strategy_src,
    strategy_vse,
    strategy_ny_br_pure,
    strategy_ny_br_ema,
    strategy_ny_br_mom,
    strategy_sp2_base,
    strategy_sp2_htf_ema,
    strategy_sp2_htf_adx,
    pm_volatility_squeeze_retest_m5,
    prev_day_sweep_reversion_pm,
    asia_london_sweep_reversion_pm,
    midday_false_break_range,
    midday_range_breakout_continuation,
    h1_trend_pullback_pm,
    adr_exhaustion_fade,
    h1_inside_bar_break_pm,
    daily_open_mean_reversion_pm,
    ict_silver_bullet_pm,
    zscore_mean_reversion_pm,
    donchian_intraday_breakout,
    adx_momentum_breakout,
    turtle_soup_fade,
    nr7_breakout,
    triple_macd_filter,
    ema_alignment_9_21_50,
    larry_connors_rsi2,
    ict_fvg_liquidity_gap,
    h1_aligned_fvg,
    h1_trend_pullback_v2,
    h1_gated_zscore,
    london_sweep_reversion_pm,
    asia_sweep_reversion_pm,
    prev_day_extrema_sweep,
    ict_atomic_sweep_displacement_pm,
    ict_atomic_sweep_fvg_pm,
    ict_atomic_sweep_choch_fvg_pm,
    ict_ifvg_repricing_pm,
    am_silver_bullet_ny_v2,
    am_opening_drive_reversal,
    am_opening_range_expansion_retest,
    eurusd_h1_liquidity_sweep_m15,
    eurusd_am_post_news_external_liquidity_shift,
    campaign3_extended_session_sweep,
    campaign3_midday_daily_reclaim,
    campaign3_post_news_continuation,
    campaign3_afternoon_compression_breakout,
    campaign3_london_ny_hybrid,
    campaign3_late_session_momentum,
    campaign3_mtf_alignment,
    campaign3b_midday_reclaim,
    campaign3b_compression_breakout,
    campaign3b_post_news_continuation,
    campaign3b_session_expansion,
    eurusd_c4_ict_align,
)


STRATEGY_REGISTRY = {
    bollinger_mean_reversion_simple.NAME: bollinger_mean_reversion_simple,
    ema_trend_pullback.NAME: ema_trend_pullback,
    bollinger_mean_reversion_adx_low.NAME: bollinger_mean_reversion_adx_low,
    donchian_breakout_regime.NAME: donchian_breakout_regime,
    keltner_volatility_expansion_simple.NAME: keltner_volatility_expansion_simple,
    keltner_squeeze_breakout.NAME: keltner_squeeze_breakout,
    supertrend_ema_filter.NAME: supertrend_ema_filter,
    strategy_smr.NAME: strategy_smr,
    strategy_ls_sr.NAME: strategy_ls_sr,
    strategy_src.NAME: strategy_src,
    strategy_vse.NAME: strategy_vse,
    strategy_ny_br_pure.NAME: strategy_ny_br_pure,
    strategy_ny_br_ema.NAME: strategy_ny_br_ema,
    strategy_ny_br_mom.NAME: strategy_ny_br_mom,
    strategy_sp2_base.NAME: strategy_sp2_base,
    strategy_sp2_htf_ema.NAME: strategy_sp2_htf_ema,
    strategy_sp2_htf_adx.NAME: strategy_sp2_htf_adx,
    pm_volatility_squeeze_retest_m5.NAME: pm_volatility_squeeze_retest_m5,
    prev_day_sweep_reversion_pm.NAME: prev_day_sweep_reversion_pm,
    asia_london_sweep_reversion_pm.NAME: asia_london_sweep_reversion_pm,
    midday_false_break_range.NAME: midday_false_break_range,
    midday_range_breakout_continuation.NAME: midday_range_breakout_continuation,
    h1_trend_pullback_pm.NAME: h1_trend_pullback_pm,
    adr_exhaustion_fade.NAME: adr_exhaustion_fade,
    h1_inside_bar_break_pm.NAME: h1_inside_bar_break_pm,
    daily_open_mean_reversion_pm.NAME: daily_open_mean_reversion_pm,
    ict_silver_bullet_pm.NAME: ict_silver_bullet_pm,
    zscore_mean_reversion_pm.NAME: zscore_mean_reversion_pm,
    donchian_intraday_breakout.NAME: donchian_intraday_breakout,
    adx_momentum_breakout.NAME: adx_momentum_breakout,
    turtle_soup_fade.NAME: turtle_soup_fade,
    nr7_breakout.NAME: nr7_breakout,
    triple_macd_filter.NAME: triple_macd_filter,
    ema_alignment_9_21_50.NAME: ema_alignment_9_21_50,
    larry_connors_rsi2.NAME: larry_connors_rsi2,
    ict_fvg_liquidity_gap.NAME: ict_fvg_liquidity_gap,
    h1_aligned_fvg.NAME: h1_aligned_fvg,
    h1_trend_pullback_v2.NAME: h1_trend_pullback_v2,
    h1_gated_zscore.NAME: h1_gated_zscore,
    london_sweep_reversion_pm.NAME: london_sweep_reversion_pm,
    asia_sweep_reversion_pm.NAME: asia_sweep_reversion_pm,
    prev_day_extrema_sweep.NAME: prev_day_extrema_sweep,
    ict_atomic_sweep_displacement_pm.NAME: ict_atomic_sweep_displacement_pm,
    ict_atomic_sweep_fvg_pm.NAME: ict_atomic_sweep_fvg_pm,
    ict_atomic_sweep_choch_fvg_pm.NAME: ict_atomic_sweep_choch_fvg_pm,
    ict_ifvg_repricing_pm.NAME: ict_ifvg_repricing_pm,
    am_silver_bullet_ny_v2.NAME: am_silver_bullet_ny_v2,
    am_opening_drive_reversal.NAME: am_opening_drive_reversal,
    am_opening_range_expansion_retest.NAME: am_opening_range_expansion_retest,
    eurusd_h1_liquidity_sweep_m15.NAME: eurusd_h1_liquidity_sweep_m15,
    eurusd_am_post_news_external_liquidity_shift.NAME: eurusd_am_post_news_external_liquidity_shift,
    campaign3_extended_session_sweep.NAME: campaign3_extended_session_sweep,
    campaign3_midday_daily_reclaim.NAME: campaign3_midday_daily_reclaim,
    campaign3_post_news_continuation.NAME: campaign3_post_news_continuation,
    campaign3_afternoon_compression_breakout.NAME: campaign3_afternoon_compression_breakout,
    campaign3_london_ny_hybrid.NAME: campaign3_london_ny_hybrid,
    campaign3_late_session_momentum.NAME: campaign3_late_session_momentum,
    campaign3_mtf_alignment.NAME: campaign3_mtf_alignment,
    campaign3b_midday_reclaim.NAME: campaign3b_midday_reclaim,
    campaign3b_compression_breakout.NAME: campaign3b_compression_breakout,
    campaign3b_post_news_continuation.NAME: campaign3b_post_news_continuation,
    campaign3b_session_expansion.NAME: campaign3b_session_expansion,
    eurusd_c4_ict_align.NAME: eurusd_c4_ict_align,
}
